apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: demo
  labels:
    app: worker
    app.kubernetes.io/part-of: test-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/part-of: test-data
    spec:
      containers:
        - name: worker
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - |
              i=0
              while true; do
                i=$((i+1))
                echo "$(date -u +%H:%M:%S) [demo/worker] job=$i done"
                sleep 2
              done
---
apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: demo
  labels:
    app: test
    logger: demo
    app.kubernetes.io/part-of: test-data
spec:
  containers:
    - name: logger
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "$(date -u +%H:%M:%S) [demo/logger] demo tick"
            sleep 3
          done
