apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    app.kubernetes.io/part-of: test-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
  labels:
    app.kubernetes.io/part-of: test-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: test-data
