apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: deployment-patch.yaml

secretGenerator:
  - name: k8s-agent-http-token
    literals:
      - token=change-me-in-production
  - name: k8s-agent-internal-token
    literals:
      - token=change-me-internal-in-production
  - name: k8s-agent-kafka-tls
    files:
      - ca.crt=secrets/kafka-ca.crt.placeholder
      - tls.crt=secrets/kafka-client.crt.placeholder
      - tls.key=secrets/kafka-client.key.placeholder
