apiVersion: v1
kind: Service
metadata:
  name: k8s-agent-http
  namespace: uamc-agent
  labels:
    app.kubernetes.io/part-of: uamc-agent
    app.kubernetes.io/component: ingress
spec:
  selector:
    app.kubernetes.io/part-of: uamc-agent
    app.kubernetes.io/component: ingress
  ports:
    - name: http
      port: 8080
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: agent-service-http
  namespace: uamc-agent
  labels:
    app.kubernetes.io/part-of: uamc-agent
    app.kubernetes.io/component: agent-service
spec:
  selector:
    app.kubernetes.io/part-of: uamc-agent
    app.kubernetes.io/component: agent-service
    k8s-agent/leader: "true"
  ports:
    - name: internal
      port: 8081
      targetPort: internal
