apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: k8s-agent-policy
    behavior: merge
    files:
      - namespaces.yaml=policy/namespaces.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: host.docker.internal:9092
    target:
      kind: Deployment
      name: k8s-agent
